# Generated by Django 5.2 on 2025-06-07 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('activation_code', models.CharField(blank=True, max_length=6, null=True)),
                ('reset_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BellTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bell_template',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('pk_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=420)),
                ('floor', models.IntegerField()),
                ('building', models.IntegerField()),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('pk_message', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('isprimary', models.IntegerField()),
                ('isshowing', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('pk_news', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('small_text', models.TextField()),
                ('main_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_displayed', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='BellSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bell_type', models.CharField(choices=[('lesson', 'Звонок на урок'), ('break', 'Звонок на перемену')], max_length=10)),
                ('scheduled_time', models.TimeField()),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.belltemplate')),
            ],
            options={
                'db_table': 'bell_schedule',
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_entries',
            },
        ),
    ]
