# Generated by Django 5.1.4 on 2024-12-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='middle_name',
            new_name='middlename',
        ),
    ]
