# Generated by Django 5.2 on 2025-05-02 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_first_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BellSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bell_type', models.CharField(choices=[('lesson', 'Звонок на урок'), ('break', 'Звонок на перемену')], max_length=10)),
                ('scheduled_time', models.TimeField()),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bell_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BellTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bell_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayedNews',
            fields=[
                ('fk_news', models.OneToOneField(db_column='fk_news', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.news')),
                ('created_at', models.DateTimeField()),
                ('display_order', models.IntegerField()),
            ],
            options={
                'db_table': 'displayed_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('pk_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=420)),
                ('floor', models.IntegerField()),
                ('building', models.IntegerField()),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('pk_video', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
