# Generated by Django 5.2 on 2025-05-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bellschedule_belltemplate_displayednews_client_video_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logentry',
            table='log_entries',
        ),
    ]
